### ISSUE TITLE
glCapsViewer 1.1 crashes on January 2017 AMD Windows 10 drivers

### ISSUE THREAD

**Issue by Groovounet** [SaschaWillems/glCapsViewer#16]

**Comment by SaschaWillems** [comment]
Thx for the info. Will try to check with AMD hardware and recent drivers on Windows 10 this weekend.

**Comment by SaschaWillems** [comment]
Sry for the late reply, but I wasn't able to reproduce. Can you save the report to disk and attach it to this issue?

**Comment by Groovounet** [comment]
Ahhh, I don't know what happen but the issue is now resolved, I could upload the report without any issue. Ohh well!
