### ISSUE TITLE
Don't submit anything to the net (including checking in the db) before it is explicitly requested by a user

### ISSUE THREAD

**Issue by KOLANICH** [SaschaWillems/glCapsViewer#24]

**Comment by SaschaWillems** [comment]
Please provided at least some description.

**Comment by KOLANICH** [comment]
https://github.com/SaschaWillems/glCapsViewer/blob/c65a7efb5e2e7d0fa84c2f7fa5ed73622135ef28/glCapsViewer.cpp#L385

**Comment by KOLANICH** [comment]
I don't see it is solved.

**Comment by SaschaWillems** [comment]
I don't plan on changing this.
