### ISSUE TITLE
url of the database must not be hardcoded, instead it must be configured in the settings

### ISSUE THREAD

**Issue by KOLANICH** [SaschaWillems/glCapsViewer#25]

**Comment by SaschaWillems** [comment]
Care to elaborate? Why would I want to change the url of the database?

**Comment by KOLANICH** [comment]
Because it is conceptually incorrect to hardcode these addresses. For example in order to replace http:// to https:// I had to rebuild the app. End users have no such an option - they have neither compiler, nor Qt, nor other needed libs.

**Comment by SaschaWillems** [comment]
I don't have any plans to change this.
