### ISSUE TITLE
Database should be explorable without any JavaScript

### ISSUE THREAD

**Issue by KOLANICH** [SaschaWillems/glCapsViewer#26]

**Comment by SaschaWillems** [comment]
Can you elaborate? The web page is the front-end to the database, along with a few m2m apis.

**Comment by KOLANICH** [comment]
The webpage doesn't worrk when JS is disabled. It should work. For example there should be code generating html server side.

**Comment by SaschaWillems** [comment]
I don't have plans to change this behaviour.
