### ISSUE TITLE
Vista - doesn't run there

### ISSUE THREAD

**Issue by Torinde** [SaschaWillems/glCapsViewer#37]
Nice tool!

In Vista (inside Virtualbox) in doesn't work. What's the minimum Windows version it supports?

For emulators and hypervisors it'll be useful to go as low as possible, e.g. NT3.x and Win95 - can you please upload somewhere the Delphi / Free Pascal version?

**Comment by SaschaWillems** [comment]
What does "doesn't work" mean? Can you please elaborate?

**Comment by Torinde** [comment]
Vista x86 message about Qt:
![image](https://github.com/user-attachments/assets/76ac67bf-abf3-474c-ad3a-32a6e7f92037)


Vista x64 message about crt, but I see vcruntime140.dll in the folder... should I install some other Visual C++ redistributable?
![image](https://github.com/user-attachments/assets/f01efcdb-117c-4a06-b8a1-ec70fc1b4180)

**Comment by SaschaWillems** [comment]
Sorry, can't help with this. I don't think Qt supports Vista anymore and I have no plans to add support for an outdated/no longer maintained operating system.

**Comment by Torinde** [comment]
OK, can you then please share the Delphi / Free Pascal version?

**Comment by SaschaWillems** [comment]
There is no up-to-ate Delphi / FP version that would work with the current version of the database.

**Comment by Torinde** [comment]
I think it'll be useful even with an older database:
- older hardware is commonly used with older OS versions
- virtualization/emulation drivers such as Mesa/SoftGPU/VboxVGA/VboxSVGA/etc. probably aren't in the database anyway (would be nice to have them though)?
  - glCapsViewer 1.2 works for me on Win11 guest with VboxSVGA 3D, I'm not sure if it's using a database or querying the system
  - what features will be missing if there's no/old database?

**Comment by SaschaWillems** [comment]
I won't add support for such old operating systems.

**Comment by Torinde** [comment]
> I won't add support for such old operating systems.

Maybe I don't understand something, but isn't it possible that the Delphi/Free Pascal version already works on an older OS than the current version? Can you please upload this old version, just to try if it works there? Or you already know it won't work?
